<e>  ::=  <e>+<e>|
          <e>-<e>|
          <e>*<e>|
          <e>**<pow>|
          pdiv(<e>,<e>)|
          psqrt(<e>)|
          np.sin(<e>)|
          np.cos(<e>)|
          np.tanh(<e>)|
          exp(<e>)|
          plog(<e>)|
          x[0]|x[1]|x[2]|
          <c1><c>.<c><c>
<pow>  ::= 2 | 3
<c1>  ::= 0 | 1 | 2 | 3 | 4
<c>  ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
